@startuml
title Our analysis of the a.c. system based on the dataset

interface "Coolant Inlet" as Inlet
interface "Coolant Outlet" as Outlet
class "Air Conditioning" as AC {
    aircon_power_kw
}
class "High Voltage Heater" as Heater {
    coolant_temperature_heatercore_c
    ---
    heater_signal
    requested_heating_power_w
    ---
    heater_voltage_v
    heater_current_a
    heating_power_can_kw
}

class "Heat exchanger" as Ex {
    heat_exchanger_temperature_c
}

"From car" -> Inlet : coolant_temperature_inlet_c

Inlet ---> Heater : temperature_coolant_heater_inlet_c
Inlet ---> AC

Heater --> Ex : temperature_coolant_heater_outlet_c
AC --> Ex

Ex -> Outlet : temperature_heat_exchanger_outlet_c

Outlet -> "To car"
@enduml
